/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: battery_ageing.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "battery_ageing.pb-c.h"
void   battery_ageing_info__init
                     (BatteryAgeingInfo         *message)
{
  static BatteryAgeingInfo init_value = BATTERY_AGEING_INFO__INIT;
  *message = init_value;
}
size_t battery_ageing_info__get_packed_size
                     (const BatteryAgeingInfo *message)
{
  assert(message->base.descriptor == &battery_ageing_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t battery_ageing_info__pack
                     (const BatteryAgeingInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &battery_ageing_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t battery_ageing_info__pack_to_buffer
                     (const BatteryAgeingInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &battery_ageing_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BatteryAgeingInfo *
       battery_ageing_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BatteryAgeingInfo *)
     protobuf_c_message_unpack (&battery_ageing_info__descriptor,
                                allocator, len, data);
}
void   battery_ageing_info__free_unpacked
                     (BatteryAgeingInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &battery_ageing_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   upload_info__init
                     (UploadInfo         *message)
{
  static UploadInfo init_value = UPLOAD_INFO__INIT;
  *message = init_value;
}
size_t upload_info__get_packed_size
                     (const UploadInfo *message)
{
  assert(message->base.descriptor == &upload_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t upload_info__pack
                     (const UploadInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &upload_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t upload_info__pack_to_buffer
                     (const UploadInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &upload_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UploadInfo *
       upload_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UploadInfo *)
     protobuf_c_message_unpack (&upload_info__descriptor,
                                allocator, len, data);
}
void   upload_info__free_unpacked
                     (UploadInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &upload_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   upload_info_ack__init
                     (UploadInfoAck         *message)
{
  static UploadInfoAck init_value = UPLOAD_INFO_ACK__INIT;
  *message = init_value;
}
size_t upload_info_ack__get_packed_size
                     (const UploadInfoAck *message)
{
  assert(message->base.descriptor == &upload_info_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t upload_info_ack__pack
                     (const UploadInfoAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &upload_info_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t upload_info_ack__pack_to_buffer
                     (const UploadInfoAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &upload_info_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UploadInfoAck *
       upload_info_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UploadInfoAck *)
     protobuf_c_message_unpack (&upload_info_ack__descriptor,
                                allocator, len, data);
}
void   upload_info_ack__free_unpacked
                     (UploadInfoAck *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &upload_info_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   discharge_setting__init
                     (DischargeSetting         *message)
{
  static DischargeSetting init_value = DISCHARGE_SETTING__INIT;
  *message = init_value;
}
size_t discharge_setting__get_packed_size
                     (const DischargeSetting *message)
{
  assert(message->base.descriptor == &discharge_setting__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t discharge_setting__pack
                     (const DischargeSetting *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &discharge_setting__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t discharge_setting__pack_to_buffer
                     (const DischargeSetting *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &discharge_setting__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DischargeSetting *
       discharge_setting__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DischargeSetting *)
     protobuf_c_message_unpack (&discharge_setting__descriptor,
                                allocator, len, data);
}
void   discharge_setting__free_unpacked
                     (DischargeSetting *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &discharge_setting__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   discharge_setting_ack__init
                     (DischargeSettingAck         *message)
{
  static DischargeSettingAck init_value = DISCHARGE_SETTING_ACK__INIT;
  *message = init_value;
}
size_t discharge_setting_ack__get_packed_size
                     (const DischargeSettingAck *message)
{
  assert(message->base.descriptor == &discharge_setting_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t discharge_setting_ack__pack
                     (const DischargeSettingAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &discharge_setting_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t discharge_setting_ack__pack_to_buffer
                     (const DischargeSettingAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &discharge_setting_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DischargeSettingAck *
       discharge_setting_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DischargeSettingAck *)
     protobuf_c_message_unpack (&discharge_setting_ack__descriptor,
                                allocator, len, data);
}
void   discharge_setting_ack__free_unpacked
                     (DischargeSettingAck *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &discharge_setting_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__body__init
                     (MSGBODY         *message)
{
  static MSGBODY init_value = MSG__BODY__INIT;
  *message = init_value;
}
size_t msg__body__get_packed_size
                     (const MSGBODY *message)
{
  assert(message->base.descriptor == &msg__body__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__body__pack
                     (const MSGBODY *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__body__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__body__pack_to_buffer
                     (const MSGBODY *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__body__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MSGBODY *
       msg__body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MSGBODY *)
     protobuf_c_message_unpack (&msg__body__descriptor,
                                allocator, len, data);
}
void   msg__body__free_unpacked
                     (MSGBODY *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &msg__body__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor battery_ageing_info__field_descriptors[23] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery_sn",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, battery_sn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slot_num",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, slot_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temprature",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, temprature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "elapsed",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, elapsed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "discharging",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, discharging),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_temprature",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, _temprature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_voltage",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, _voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_fullChargecapacity",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, _fullchargecapacity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_remainingcapacity",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, _remainingcapacity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_averagecurrent",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, _averagecurrent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_cyclecount",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, _cyclecount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_bmssafetyStatus",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, _bmssafetystatus),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_bmsflags",
    16,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, _bmsflags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_batterystatus",
    17,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, _batterystatus),
    &heart__beat__battery__code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_chargestatus",
    18,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, _chargestatus),
    &charge__status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_enablestatus",
    19,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, _enablestatus),
    &enable__borrow__status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_slotstatus",
    20,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, _slotstatus),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_destroyed",
    21,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, _destroyed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_hasbms",
    22,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, _hasbms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_radio",
    23,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BatteryAgeingInfo, _radio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned battery_ageing_info__field_indices_by_name[] = {
  12,   /* field[12] = _averagecurrent */
  16,   /* field[16] = _batterystatus */
  15,   /* field[15] = _bmsflags */
  14,   /* field[14] = _bmssafetyStatus */
  17,   /* field[17] = _chargestatus */
  13,   /* field[13] = _cyclecount */
  20,   /* field[20] = _destroyed */
  18,   /* field[18] = _enablestatus */
  10,   /* field[10] = _fullChargecapacity */
  21,   /* field[21] = _hasbms */
  22,   /* field[22] = _radio */
  11,   /* field[11] = _remainingcapacity */
  19,   /* field[19] = _slotstatus */
  8,   /* field[8] = _temprature */
  9,   /* field[9] = _voltage */
  1,   /* field[1] = battery_sn */
  4,   /* field[4] = current */
  7,   /* field[7] = discharging */
  6,   /* field[6] = elapsed */
  2,   /* field[2] = slot_num */
  5,   /* field[5] = temprature */
  0,   /* field[0] = timestamp */
  3,   /* field[3] = voltage */
};
static const ProtobufCIntRange battery_ageing_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 23 }
};
const ProtobufCMessageDescriptor battery_ageing_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BatteryAgeingInfo",
  "BatteryAgeingInfo",
  "BatteryAgeingInfo",
  "",
  sizeof(BatteryAgeingInfo),
  23,
  battery_ageing_info__field_descriptors,
  battery_ageing_info__field_indices_by_name,
  1,  battery_ageing_info__number_ranges,
  (ProtobufCMessageInit) battery_ageing_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor upload_info__field_descriptors[1] =
{
  {
    "battery_ageing_info",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UploadInfo, n_battery_ageing_info),
    offsetof(UploadInfo, battery_ageing_info),
    &battery_ageing_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned upload_info__field_indices_by_name[] = {
  0,   /* field[0] = battery_ageing_info */
};
static const ProtobufCIntRange upload_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor upload_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UploadInfo",
  "UploadInfo",
  "UploadInfo",
  "",
  sizeof(UploadInfo),
  1,
  upload_info__field_descriptors,
  upload_info__field_indices_by_name,
  1,  upload_info__number_ranges,
  (ProtobufCMessageInit) upload_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor upload_info_ack__field_descriptors[1] =
{
  {
    "res",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UploadInfoAck, res),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned upload_info_ack__field_indices_by_name[] = {
  0,   /* field[0] = res */
};
static const ProtobufCIntRange upload_info_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor upload_info_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UploadInfoAck",
  "UploadInfoAck",
  "UploadInfoAck",
  "",
  sizeof(UploadInfoAck),
  1,
  upload_info_ack__field_descriptors,
  upload_info_ack__field_indices_by_name,
  1,  upload_info_ack__number_ranges,
  (ProtobufCMessageInit) upload_info_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor discharge_setting__field_descriptors[3] =
{
  {
    "slot_num",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DischargeSetting, slot_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DischargeSetting, cmd),
    &discharge__cmd__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "level",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DischargeSetting, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned discharge_setting__field_indices_by_name[] = {
  1,   /* field[1] = cmd */
  2,   /* field[2] = level */
  0,   /* field[0] = slot_num */
};
static const ProtobufCIntRange discharge_setting__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor discharge_setting__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DischargeSetting",
  "DischargeSetting",
  "DischargeSetting",
  "",
  sizeof(DischargeSetting),
  3,
  discharge_setting__field_descriptors,
  discharge_setting__field_indices_by_name,
  1,  discharge_setting__number_ranges,
  (ProtobufCMessageInit) discharge_setting__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor discharge_setting_ack__field_descriptors[3] =
{
  {
    "setting",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DischargeSettingAck, setting),
    &discharge_setting__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rcc",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DischargeSettingAck, rcc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "res",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DischargeSettingAck, res),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned discharge_setting_ack__field_indices_by_name[] = {
  1,   /* field[1] = rcc */
  2,   /* field[2] = res */
  0,   /* field[0] = setting */
};
static const ProtobufCIntRange discharge_setting_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor discharge_setting_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DischargeSettingAck",
  "DischargeSettingAck",
  "DischargeSettingAck",
  "",
  sizeof(DischargeSettingAck),
  3,
  discharge_setting_ack__field_descriptors,
  discharge_setting_ack__field_indices_by_name,
  1,  discharge_setting_ack__number_ranges,
  (ProtobufCMessageInit) discharge_setting_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__body__field_descriptors[6] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MSGBODY, type),
    &msg__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_sn",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MSGBODY, device_sn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "up_info",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MSGBODY, up_info),
    &upload_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "up_info_ack",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MSGBODY, up_info_ack),
    &upload_info_ack__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dis_setting",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MSGBODY, dis_setting),
    &discharge_setting__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dis_setting_ack",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MSGBODY, dis_setting_ack),
    &discharge_setting_ack__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__body__field_indices_by_name[] = {
  1,   /* field[1] = device_sn */
  4,   /* field[4] = dis_setting */
  5,   /* field[5] = dis_setting_ack */
  0,   /* field[0] = type */
  2,   /* field[2] = up_info */
  3,   /* field[3] = up_info_ack */
};
static const ProtobufCIntRange msg__body__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor msg__body__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MSG_BODY",
  "MSGBODY",
  "MSGBODY",
  "",
  sizeof(MSGBODY),
  6,
  msg__body__field_descriptors,
  msg__body__field_indices_by_name,
  1,  msg__body__number_ranges,
  (ProtobufCMessageInit) msg__body__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue heart__beat__battery__code__enum_values_by_number[10] =
{
  { "HBB_STATUS_OK", "HEART__BEAT__BATTERY__CODE__HBB_STATUS_OK", 0 },
  { "HBB_OTHER_ERROR", "HEART__BEAT__BATTERY__CODE__HBB_OTHER_ERROR", 1 },
  { "HBB_TEMPERATURE_ERROR", "HEART__BEAT__BATTERY__CODE__HBB_TEMPERATURE_ERROR", 2 },
  { "HBB_VOLTAGE_ERROR", "HEART__BEAT__BATTERY__CODE__HBB_VOLTAGE_ERROR", 3 },
  { "HBB_CURRENT_ERROR", "HEART__BEAT__BATTERY__CODE__HBB_CURRENT_ERROR", 4 },
  { "HBB_CYCLECOUNT_ERROR", "HEART__BEAT__BATTERY__CODE__HBB_CYCLECOUNT_ERROR", 5 },
  { "HBB_INTERFACE_ERROR", "HEART__BEAT__BATTERY__CODE__HBB_INTERFACE_ERROR", 6 },
  { "HBB_BODY_ERROR", "HEART__BEAT__BATTERY__CODE__HBB_BODY_ERROR", 7 },
  { "HBB_LINE_ERROR", "HEART__BEAT__BATTERY__CODE__HBB_LINE_ERROR", 8 },
  { "HBB_BODY_AND_LINE_ERROR", "HEART__BEAT__BATTERY__CODE__HBB_BODY_AND_LINE_ERROR", 9 },
};
static const ProtobufCIntRange heart__beat__battery__code__value_ranges[] = {
{0, 0},{0, 10}
};
static const ProtobufCEnumValueIndex heart__beat__battery__code__enum_values_by_name[10] =
{
  { "HBB_BODY_AND_LINE_ERROR", 9 },
  { "HBB_BODY_ERROR", 7 },
  { "HBB_CURRENT_ERROR", 4 },
  { "HBB_CYCLECOUNT_ERROR", 5 },
  { "HBB_INTERFACE_ERROR", 6 },
  { "HBB_LINE_ERROR", 8 },
  { "HBB_OTHER_ERROR", 1 },
  { "HBB_STATUS_OK", 0 },
  { "HBB_TEMPERATURE_ERROR", 2 },
  { "HBB_VOLTAGE_ERROR", 3 },
};
const ProtobufCEnumDescriptor heart__beat__battery__code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "HEART_BEAT_BATTERY_CODE",
  "HEART_BEAT_BATTERY_CODE",
  "HEARTBEATBATTERYCODE",
  "",
  10,
  heart__beat__battery__code__enum_values_by_number,
  10,
  heart__beat__battery__code__enum_values_by_name,
  1,
  heart__beat__battery__code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue charge__status__enum_values_by_number[3] =
{
  { "UNCHARGE", "CHARGE__STATUS__UNCHARGE", 1 },
  { "CHARGING", "CHARGE__STATUS__CHARGING", 2 },
  { "DISCHARGING", "CHARGE__STATUS__DISCHARGING", 3 },
};
static const ProtobufCIntRange charge__status__value_ranges[] = {
{1, 0},{0, 3}
};
static const ProtobufCEnumValueIndex charge__status__enum_values_by_name[3] =
{
  { "CHARGING", 1 },
  { "DISCHARGING", 2 },
  { "UNCHARGE", 0 },
};
const ProtobufCEnumDescriptor charge__status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CHARGE_STATUS",
  "CHARGE_STATUS",
  "CHARGESTATUS",
  "",
  3,
  charge__status__enum_values_by_number,
  3,
  charge__status__enum_values_by_name,
  1,
  charge__status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue enable__borrow__status__enum_values_by_number[2] =
{
  { "ENABLE_STATUS", "ENABLE__BORROW__STATUS__ENABLE_STATUS", 0 },
  { "DISABLE_STATUS", "ENABLE__BORROW__STATUS__DISABLE_STATUS", 1 },
};
static const ProtobufCIntRange enable__borrow__status__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex enable__borrow__status__enum_values_by_name[2] =
{
  { "DISABLE_STATUS", 1 },
  { "ENABLE_STATUS", 0 },
};
const ProtobufCEnumDescriptor enable__borrow__status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ENABLE_BORROW_STATUS",
  "ENABLE_BORROW_STATUS",
  "ENABLEBORROWSTATUS",
  "",
  2,
  enable__borrow__status__enum_values_by_number,
  2,
  enable__borrow__status__enum_values_by_name,
  1,
  enable__borrow__status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue discharge__cmd__enum_values_by_number[2] =
{
  { "START_DISCHARGE", "DISCHARGE__CMD__START_DISCHARGE", 1 },
  { "STOP_DISCHARGE", "DISCHARGE__CMD__STOP_DISCHARGE", 2 },
};
static const ProtobufCIntRange discharge__cmd__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex discharge__cmd__enum_values_by_name[2] =
{
  { "START_DISCHARGE", 0 },
  { "STOP_DISCHARGE", 1 },
};
const ProtobufCEnumDescriptor discharge__cmd__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DISCHARGE_CMD",
  "DISCHARGE_CMD",
  "DISCHARGECMD",
  "",
  2,
  discharge__cmd__enum_values_by_number,
  2,
  discharge__cmd__enum_values_by_name,
  1,
  discharge__cmd__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue msg__type__enum_values_by_number[4] =
{
  { "UPLOAD_INFO", "MSG__TYPE__UPLOAD_INFO", 1 },
  { "UPLOAD_INFO_ACK", "MSG__TYPE__UPLOAD_INFO_ACK", 2 },
  { "DISCHARGE_SETTING", "MSG__TYPE__DISCHARGE_SETTING", 3 },
  { "DISCHARGE_SETTING_ACK", "MSG__TYPE__DISCHARGE_SETTING_ACK", 4 },
};
static const ProtobufCIntRange msg__type__value_ranges[] = {
{1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex msg__type__enum_values_by_name[4] =
{
  { "DISCHARGE_SETTING", 2 },
  { "DISCHARGE_SETTING_ACK", 3 },
  { "UPLOAD_INFO", 0 },
  { "UPLOAD_INFO_ACK", 1 },
};
const ProtobufCEnumDescriptor msg__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MSG_TYPE",
  "MSG_TYPE",
  "MSGTYPE",
  "",
  4,
  msg__type__enum_values_by_number,
  4,
  msg__type__enum_values_by_name,
  1,
  msg__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
