/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: battery_ageing.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "battery_ageing.pb-c.h"
void   bmessage__init
                     (BMessage         *message)
{
  static BMessage init_value = BMESSAGE__INIT;
  *message = init_value;
}
size_t bmessage__get_packed_size
                     (const BMessage *message)
{
  assert(message->base.descriptor == &bmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bmessage__pack
                     (const BMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bmessage__pack_to_buffer
                     (const BMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BMessage *
       bmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BMessage *)
     protobuf_c_message_unpack (&bmessage__descriptor,
                                allocator, len, data);
}
void   bmessage__free_unpacked
                     (BMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &bmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   amessage__init
                     (AMessage         *message)
{
  static AMessage init_value = AMESSAGE__INIT;
  *message = init_value;
}
size_t amessage__get_packed_size
                     (const AMessage *message)
{
  assert(message->base.descriptor == &amessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t amessage__pack
                     (const AMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &amessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t amessage__pack_to_buffer
                     (const AMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &amessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AMessage *
       amessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AMessage *)
     protobuf_c_message_unpack (&amessage__descriptor,
                                allocator, len, data);
}
void   amessage__free_unpacked
                     (AMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &amessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor bmessage__field_descriptors[2] =
{
  {
    "m",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BMessage, m),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BMessage, n),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bmessage__field_indices_by_name[] = {
  0,   /* field[0] = m */
  1,   /* field[1] = n */
};
static const ProtobufCIntRange bmessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor bmessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BMessage",
  "BMessage",
  "BMessage",
  "",
  sizeof(BMessage),
  2,
  bmessage__field_descriptors,
  bmessage__field_indices_by_name,
  1,  bmessage__number_ranges,
  (ProtobufCMessageInit) bmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor amessage__field_descriptors[3] =
{
  {
    "a",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AMessage, a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "b",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(AMessage, has_b),
    offsetof(AMessage, b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(AMessage, n_d),
    offsetof(AMessage, d),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned amessage__field_indices_by_name[] = {
  0,   /* field[0] = a */
  1,   /* field[1] = b */
  2,   /* field[2] = d */
};
static const ProtobufCIntRange amessage__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor amessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AMessage",
  "AMessage",
  "AMessage",
  "",
  sizeof(AMessage),
  3,
  amessage__field_descriptors,
  amessage__field_indices_by_name,
  2,  amessage__number_ranges,
  (ProtobufCMessageInit) amessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
