// Code generated by protoc-gen-go. DO NOT EDIT.
// source: battery_ageing.proto

package battery_ageing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HEART_BEAT_BATTERY_CODE int32

const (
	HEART_BEAT_BATTERY_CODE_HBB_STATUS_OK           HEART_BEAT_BATTERY_CODE = 0
	HEART_BEAT_BATTERY_CODE_HBB_OTHER_ERROR         HEART_BEAT_BATTERY_CODE = 1
	HEART_BEAT_BATTERY_CODE_HBB_TEMPERATURE_ERROR   HEART_BEAT_BATTERY_CODE = 2
	HEART_BEAT_BATTERY_CODE_HBB_VOLTAGE_ERROR       HEART_BEAT_BATTERY_CODE = 3
	HEART_BEAT_BATTERY_CODE_HBB_CURRENT_ERROR       HEART_BEAT_BATTERY_CODE = 4
	HEART_BEAT_BATTERY_CODE_HBB_CYCLECOUNT_ERROR    HEART_BEAT_BATTERY_CODE = 5
	HEART_BEAT_BATTERY_CODE_HBB_INTERFACE_ERROR     HEART_BEAT_BATTERY_CODE = 6
	HEART_BEAT_BATTERY_CODE_HBB_BODY_ERROR          HEART_BEAT_BATTERY_CODE = 7
	HEART_BEAT_BATTERY_CODE_HBB_LINE_ERROR          HEART_BEAT_BATTERY_CODE = 8
	HEART_BEAT_BATTERY_CODE_HBB_BODY_AND_LINE_ERROR HEART_BEAT_BATTERY_CODE = 9
)

var HEART_BEAT_BATTERY_CODE_name = map[int32]string{
	0: "HBB_STATUS_OK",
	1: "HBB_OTHER_ERROR",
	2: "HBB_TEMPERATURE_ERROR",
	3: "HBB_VOLTAGE_ERROR",
	4: "HBB_CURRENT_ERROR",
	5: "HBB_CYCLECOUNT_ERROR",
	6: "HBB_INTERFACE_ERROR",
	7: "HBB_BODY_ERROR",
	8: "HBB_LINE_ERROR",
	9: "HBB_BODY_AND_LINE_ERROR",
}

var HEART_BEAT_BATTERY_CODE_value = map[string]int32{
	"HBB_STATUS_OK":           0,
	"HBB_OTHER_ERROR":         1,
	"HBB_TEMPERATURE_ERROR":   2,
	"HBB_VOLTAGE_ERROR":       3,
	"HBB_CURRENT_ERROR":       4,
	"HBB_CYCLECOUNT_ERROR":    5,
	"HBB_INTERFACE_ERROR":     6,
	"HBB_BODY_ERROR":          7,
	"HBB_LINE_ERROR":          8,
	"HBB_BODY_AND_LINE_ERROR": 9,
}

func (x HEART_BEAT_BATTERY_CODE) Enum() *HEART_BEAT_BATTERY_CODE {
	p := new(HEART_BEAT_BATTERY_CODE)
	*p = x
	return p
}

func (x HEART_BEAT_BATTERY_CODE) String() string {
	return proto.EnumName(HEART_BEAT_BATTERY_CODE_name, int32(x))
}

func (x *HEART_BEAT_BATTERY_CODE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HEART_BEAT_BATTERY_CODE_value, data, "HEART_BEAT_BATTERY_CODE")
	if err != nil {
		return err
	}
	*x = HEART_BEAT_BATTERY_CODE(value)
	return nil
}

func (HEART_BEAT_BATTERY_CODE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23ea8d3492947939, []int{0}
}

type CHARGE_STATUS int32

const (
	CHARGE_STATUS_UNCHARGE    CHARGE_STATUS = 1
	CHARGE_STATUS_CHARGING    CHARGE_STATUS = 2
	CHARGE_STATUS_DISCHARGING CHARGE_STATUS = 3
)

var CHARGE_STATUS_name = map[int32]string{
	1: "UNCHARGE",
	2: "CHARGING",
	3: "DISCHARGING",
}

var CHARGE_STATUS_value = map[string]int32{
	"UNCHARGE":    1,
	"CHARGING":    2,
	"DISCHARGING": 3,
}

func (x CHARGE_STATUS) Enum() *CHARGE_STATUS {
	p := new(CHARGE_STATUS)
	*p = x
	return p
}

func (x CHARGE_STATUS) String() string {
	return proto.EnumName(CHARGE_STATUS_name, int32(x))
}

func (x *CHARGE_STATUS) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CHARGE_STATUS_value, data, "CHARGE_STATUS")
	if err != nil {
		return err
	}
	*x = CHARGE_STATUS(value)
	return nil
}

func (CHARGE_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23ea8d3492947939, []int{1}
}

type ENABLE_BORROW_STATUS int32

const (
	ENABLE_BORROW_STATUS_ENABLE_STATUS  ENABLE_BORROW_STATUS = 0
	ENABLE_BORROW_STATUS_DISABLE_STATUS ENABLE_BORROW_STATUS = 1
)

var ENABLE_BORROW_STATUS_name = map[int32]string{
	0: "ENABLE_STATUS",
	1: "DISABLE_STATUS",
}

var ENABLE_BORROW_STATUS_value = map[string]int32{
	"ENABLE_STATUS":  0,
	"DISABLE_STATUS": 1,
}

func (x ENABLE_BORROW_STATUS) Enum() *ENABLE_BORROW_STATUS {
	p := new(ENABLE_BORROW_STATUS)
	*p = x
	return p
}

func (x ENABLE_BORROW_STATUS) String() string {
	return proto.EnumName(ENABLE_BORROW_STATUS_name, int32(x))
}

func (x *ENABLE_BORROW_STATUS) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ENABLE_BORROW_STATUS_value, data, "ENABLE_BORROW_STATUS")
	if err != nil {
		return err
	}
	*x = ENABLE_BORROW_STATUS(value)
	return nil
}

func (ENABLE_BORROW_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23ea8d3492947939, []int{2}
}

type DISCHARGE_CMD int32

const (
	DISCHARGE_CMD_START_DISCHARGE DISCHARGE_CMD = 1
	DISCHARGE_CMD_STOP_DISCHARGE  DISCHARGE_CMD = 2
)

var DISCHARGE_CMD_name = map[int32]string{
	1: "START_DISCHARGE",
	2: "STOP_DISCHARGE",
}

var DISCHARGE_CMD_value = map[string]int32{
	"START_DISCHARGE": 1,
	"STOP_DISCHARGE":  2,
}

func (x DISCHARGE_CMD) Enum() *DISCHARGE_CMD {
	p := new(DISCHARGE_CMD)
	*p = x
	return p
}

func (x DISCHARGE_CMD) String() string {
	return proto.EnumName(DISCHARGE_CMD_name, int32(x))
}

func (x *DISCHARGE_CMD) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DISCHARGE_CMD_value, data, "DISCHARGE_CMD")
	if err != nil {
		return err
	}
	*x = DISCHARGE_CMD(value)
	return nil
}

func (DISCHARGE_CMD) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23ea8d3492947939, []int{3}
}

type MSG_TYPE int32

const (
	MSG_TYPE_UPLOAD_INFO       MSG_TYPE = 1
	MSG_TYPE_DISCHARGE_SETTING MSG_TYPE = 2
)

var MSG_TYPE_name = map[int32]string{
	1: "UPLOAD_INFO",
	2: "DISCHARGE_SETTING",
}

var MSG_TYPE_value = map[string]int32{
	"UPLOAD_INFO":       1,
	"DISCHARGE_SETTING": 2,
}

func (x MSG_TYPE) Enum() *MSG_TYPE {
	p := new(MSG_TYPE)
	*p = x
	return p
}

func (x MSG_TYPE) String() string {
	return proto.EnumName(MSG_TYPE_name, int32(x))
}

func (x *MSG_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MSG_TYPE_value, data, "MSG_TYPE")
	if err != nil {
		return err
	}
	*x = MSG_TYPE(value)
	return nil
}

func (MSG_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23ea8d3492947939, []int{4}
}

type BatteryAgeingInfo struct {
	Timestamp            *string                  `protobuf:"bytes,1,req,name=timestamp" json:"timestamp,omitempty"`
	BatterySn            *string                  `protobuf:"bytes,2,req,name=battery_sn" json:"battery_sn,omitempty"`
	SlotNum              *int32                   `protobuf:"varint,3,req,name=slot_num" json:"slot_num,omitempty"`
	Voltage              *int32                   `protobuf:"varint,4,req,name=voltage" json:"voltage,omitempty"`
	Current              *int32                   `protobuf:"varint,5,req,name=current" json:"current,omitempty"`
	Temprature           *int32                   `protobuf:"varint,6,req,name=temprature" json:"temprature,omitempty"`
	Elapsed              *int32                   `protobuf:"varint,7,req,name=elapsed" json:"elapsed,omitempty"`
	Discharging          *int32                   `protobuf:"varint,8,req,name=discharging" json:"discharging,omitempty"`
	XTemprature          *int32                   `protobuf:"varint,9,req,name=_temprature" json:"_temprature,omitempty"`
	XVoltage             *int32                   `protobuf:"varint,10,req,name=_voltage" json:"_voltage,omitempty"`
	XFullChargecapacity  *int32                   `protobuf:"varint,11,req,name=_fullChargecapacity" json:"_fullChargecapacity,omitempty"`
	XRemainingcapacity   *int32                   `protobuf:"varint,12,req,name=_remainingcapacity" json:"_remainingcapacity,omitempty"`
	XAveragecurrent      *int32                   `protobuf:"varint,13,req,name=_averagecurrent" json:"_averagecurrent,omitempty"`
	XCyclecount          *int32                   `protobuf:"varint,14,req,name=_cyclecount" json:"_cyclecount,omitempty"`
	XBmssafetyStatus     *int32                   `protobuf:"varint,15,req,name=_bmssafetyStatus" json:"_bmssafetyStatus,omitempty"`
	XBmsflags            *int32                   `protobuf:"varint,16,req,name=_bmsflags" json:"_bmsflags,omitempty"`
	XBatterystatus       *HEART_BEAT_BATTERY_CODE `protobuf:"varint,17,req,name=_batterystatus,enum=HEART_BEAT_BATTERY_CODE" json:"_batterystatus,omitempty"`
	XChargestatus        *CHARGE_STATUS           `protobuf:"varint,18,req,name=_chargestatus,enum=CHARGE_STATUS" json:"_chargestatus,omitempty"`
	XEnablestatus        *ENABLE_BORROW_STATUS    `protobuf:"varint,19,req,name=_enablestatus,enum=ENABLE_BORROW_STATUS" json:"_enablestatus,omitempty"`
	XSlotstatus          *int32                   `protobuf:"varint,20,req,name=_slotstatus" json:"_slotstatus,omitempty"`
	XDestroyed           *int32                   `protobuf:"varint,21,req,name=_destroyed" json:"_destroyed,omitempty"`
	XHasbms              *int32                   `protobuf:"varint,22,req,name=_hasbms" json:"_hasbms,omitempty"`
	XRadio               *int32                   `protobuf:"varint,23,req,name=_radio" json:"_radio,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *BatteryAgeingInfo) Reset()         { *m = BatteryAgeingInfo{} }
func (m *BatteryAgeingInfo) String() string { return proto.CompactTextString(m) }
func (*BatteryAgeingInfo) ProtoMessage()    {}
func (*BatteryAgeingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_23ea8d3492947939, []int{0}
}

func (m *BatteryAgeingInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatteryAgeingInfo.Unmarshal(m, b)
}
func (m *BatteryAgeingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatteryAgeingInfo.Marshal(b, m, deterministic)
}
func (m *BatteryAgeingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatteryAgeingInfo.Merge(m, src)
}
func (m *BatteryAgeingInfo) XXX_Size() int {
	return xxx_messageInfo_BatteryAgeingInfo.Size(m)
}
func (m *BatteryAgeingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BatteryAgeingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BatteryAgeingInfo proto.InternalMessageInfo

func (m *BatteryAgeingInfo) GetTimestamp() string {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return ""
}

func (m *BatteryAgeingInfo) GetBatterySn() string {
	if m != nil && m.BatterySn != nil {
		return *m.BatterySn
	}
	return ""
}

func (m *BatteryAgeingInfo) GetSlotNum() int32 {
	if m != nil && m.SlotNum != nil {
		return *m.SlotNum
	}
	return 0
}

func (m *BatteryAgeingInfo) GetVoltage() int32 {
	if m != nil && m.Voltage != nil {
		return *m.Voltage
	}
	return 0
}

func (m *BatteryAgeingInfo) GetCurrent() int32 {
	if m != nil && m.Current != nil {
		return *m.Current
	}
	return 0
}

func (m *BatteryAgeingInfo) GetTemprature() int32 {
	if m != nil && m.Temprature != nil {
		return *m.Temprature
	}
	return 0
}

func (m *BatteryAgeingInfo) GetElapsed() int32 {
	if m != nil && m.Elapsed != nil {
		return *m.Elapsed
	}
	return 0
}

func (m *BatteryAgeingInfo) GetDischarging() int32 {
	if m != nil && m.Discharging != nil {
		return *m.Discharging
	}
	return 0
}

func (m *BatteryAgeingInfo) GetXTemprature() int32 {
	if m != nil && m.XTemprature != nil {
		return *m.XTemprature
	}
	return 0
}

func (m *BatteryAgeingInfo) GetXVoltage() int32 {
	if m != nil && m.XVoltage != nil {
		return *m.XVoltage
	}
	return 0
}

func (m *BatteryAgeingInfo) GetXFullChargecapacity() int32 {
	if m != nil && m.XFullChargecapacity != nil {
		return *m.XFullChargecapacity
	}
	return 0
}

func (m *BatteryAgeingInfo) GetXRemainingcapacity() int32 {
	if m != nil && m.XRemainingcapacity != nil {
		return *m.XRemainingcapacity
	}
	return 0
}

func (m *BatteryAgeingInfo) GetXAveragecurrent() int32 {
	if m != nil && m.XAveragecurrent != nil {
		return *m.XAveragecurrent
	}
	return 0
}

func (m *BatteryAgeingInfo) GetXCyclecount() int32 {
	if m != nil && m.XCyclecount != nil {
		return *m.XCyclecount
	}
	return 0
}

func (m *BatteryAgeingInfo) GetXBmssafetyStatus() int32 {
	if m != nil && m.XBmssafetyStatus != nil {
		return *m.XBmssafetyStatus
	}
	return 0
}

func (m *BatteryAgeingInfo) GetXBmsflags() int32 {
	if m != nil && m.XBmsflags != nil {
		return *m.XBmsflags
	}
	return 0
}

func (m *BatteryAgeingInfo) GetXBatterystatus() HEART_BEAT_BATTERY_CODE {
	if m != nil && m.XBatterystatus != nil {
		return *m.XBatterystatus
	}
	return HEART_BEAT_BATTERY_CODE_HBB_STATUS_OK
}

func (m *BatteryAgeingInfo) GetXChargestatus() CHARGE_STATUS {
	if m != nil && m.XChargestatus != nil {
		return *m.XChargestatus
	}
	return CHARGE_STATUS_UNCHARGE
}

func (m *BatteryAgeingInfo) GetXEnablestatus() ENABLE_BORROW_STATUS {
	if m != nil && m.XEnablestatus != nil {
		return *m.XEnablestatus
	}
	return ENABLE_BORROW_STATUS_ENABLE_STATUS
}

func (m *BatteryAgeingInfo) GetXSlotstatus() int32 {
	if m != nil && m.XSlotstatus != nil {
		return *m.XSlotstatus
	}
	return 0
}

func (m *BatteryAgeingInfo) GetXDestroyed() int32 {
	if m != nil && m.XDestroyed != nil {
		return *m.XDestroyed
	}
	return 0
}

func (m *BatteryAgeingInfo) GetXHasbms() int32 {
	if m != nil && m.XHasbms != nil {
		return *m.XHasbms
	}
	return 0
}

func (m *BatteryAgeingInfo) GetXRadio() int32 {
	if m != nil && m.XRadio != nil {
		return *m.XRadio
	}
	return 0
}

type UploadInfo struct {
	BatteryAgeingInfo    []*BatteryAgeingInfo `protobuf:"bytes,1,rep,name=battery_ageing_info" json:"battery_ageing_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UploadInfo) Reset()         { *m = UploadInfo{} }
func (m *UploadInfo) String() string { return proto.CompactTextString(m) }
func (*UploadInfo) ProtoMessage()    {}
func (*UploadInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_23ea8d3492947939, []int{1}
}

func (m *UploadInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadInfo.Unmarshal(m, b)
}
func (m *UploadInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadInfo.Marshal(b, m, deterministic)
}
func (m *UploadInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadInfo.Merge(m, src)
}
func (m *UploadInfo) XXX_Size() int {
	return xxx_messageInfo_UploadInfo.Size(m)
}
func (m *UploadInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UploadInfo proto.InternalMessageInfo

func (m *UploadInfo) GetBatteryAgeingInfo() []*BatteryAgeingInfo {
	if m != nil {
		return m.BatteryAgeingInfo
	}
	return nil
}

type DischargeSetting struct {
	MachineId            *string        `protobuf:"bytes,1,req,name=machine_id" json:"machine_id,omitempty"`
	SlotNum              *int32         `protobuf:"varint,2,req,name=slot_num" json:"slot_num,omitempty"`
	Cmd                  *DISCHARGE_CMD `protobuf:"varint,3,req,name=cmd,enum=DISCHARGE_CMD" json:"cmd,omitempty"`
	Level                *int32         `protobuf:"varint,4,req,name=level" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DischargeSetting) Reset()         { *m = DischargeSetting{} }
func (m *DischargeSetting) String() string { return proto.CompactTextString(m) }
func (*DischargeSetting) ProtoMessage()    {}
func (*DischargeSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_23ea8d3492947939, []int{2}
}

func (m *DischargeSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DischargeSetting.Unmarshal(m, b)
}
func (m *DischargeSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DischargeSetting.Marshal(b, m, deterministic)
}
func (m *DischargeSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DischargeSetting.Merge(m, src)
}
func (m *DischargeSetting) XXX_Size() int {
	return xxx_messageInfo_DischargeSetting.Size(m)
}
func (m *DischargeSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_DischargeSetting.DiscardUnknown(m)
}

var xxx_messageInfo_DischargeSetting proto.InternalMessageInfo

func (m *DischargeSetting) GetMachineId() string {
	if m != nil && m.MachineId != nil {
		return *m.MachineId
	}
	return ""
}

func (m *DischargeSetting) GetSlotNum() int32 {
	if m != nil && m.SlotNum != nil {
		return *m.SlotNum
	}
	return 0
}

func (m *DischargeSetting) GetCmd() DISCHARGE_CMD {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return DISCHARGE_CMD_START_DISCHARGE
}

func (m *DischargeSetting) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type MSG_BODY struct {
	Type                 *MSG_TYPE         `protobuf:"varint,1,req,name=type,enum=MSG_TYPE" json:"type,omitempty"`
	UpInfo               *UploadInfo       `protobuf:"bytes,2,opt,name=up_info" json:"up_info,omitempty"`
	DisSetting           *DischargeSetting `protobuf:"bytes,3,opt,name=dis_setting" json:"dis_setting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MSG_BODY) Reset()         { *m = MSG_BODY{} }
func (m *MSG_BODY) String() string { return proto.CompactTextString(m) }
func (*MSG_BODY) ProtoMessage()    {}
func (*MSG_BODY) Descriptor() ([]byte, []int) {
	return fileDescriptor_23ea8d3492947939, []int{3}
}

func (m *MSG_BODY) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MSG_BODY.Unmarshal(m, b)
}
func (m *MSG_BODY) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MSG_BODY.Marshal(b, m, deterministic)
}
func (m *MSG_BODY) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MSG_BODY.Merge(m, src)
}
func (m *MSG_BODY) XXX_Size() int {
	return xxx_messageInfo_MSG_BODY.Size(m)
}
func (m *MSG_BODY) XXX_DiscardUnknown() {
	xxx_messageInfo_MSG_BODY.DiscardUnknown(m)
}

var xxx_messageInfo_MSG_BODY proto.InternalMessageInfo

func (m *MSG_BODY) GetType() MSG_TYPE {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return MSG_TYPE_UPLOAD_INFO
}

func (m *MSG_BODY) GetUpInfo() *UploadInfo {
	if m != nil {
		return m.UpInfo
	}
	return nil
}

func (m *MSG_BODY) GetDisSetting() *DischargeSetting {
	if m != nil {
		return m.DisSetting
	}
	return nil
}

func init() {
	proto.RegisterEnum("HEART_BEAT_BATTERY_CODE", HEART_BEAT_BATTERY_CODE_name, HEART_BEAT_BATTERY_CODE_value)
	proto.RegisterEnum("CHARGE_STATUS", CHARGE_STATUS_name, CHARGE_STATUS_value)
	proto.RegisterEnum("ENABLE_BORROW_STATUS", ENABLE_BORROW_STATUS_name, ENABLE_BORROW_STATUS_value)
	proto.RegisterEnum("DISCHARGE_CMD", DISCHARGE_CMD_name, DISCHARGE_CMD_value)
	proto.RegisterEnum("MSG_TYPE", MSG_TYPE_name, MSG_TYPE_value)
	proto.RegisterType((*BatteryAgeingInfo)(nil), "BatteryAgeingInfo")
	proto.RegisterType((*UploadInfo)(nil), "UploadInfo")
	proto.RegisterType((*DischargeSetting)(nil), "DischargeSetting")
	proto.RegisterType((*MSG_BODY)(nil), "MSG_BODY")
}

func init() { proto.RegisterFile("battery_ageing.proto", fileDescriptor_23ea8d3492947939) }

var fileDescriptor_23ea8d3492947939 = []byte{
	// 771 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcb, 0x8f, 0xea, 0x36,
	0x14, 0xc6, 0x2f, 0x61, 0x1e, 0x70, 0xb8, 0x40, 0x30, 0x33, 0xc5, 0xed, 0xed, 0x02, 0x8d, 0xd4,
	0x0a, 0xa1, 0x8a, 0x56, 0xac, 0xba, 0xe8, 0x5d, 0x04, 0xf0, 0x9d, 0x41, 0x65, 0xc8, 0x28, 0x31,
	0xad, 0x66, 0x65, 0x79, 0x12, 0x93, 0x89, 0x94, 0x07, 0x4a, 0xcc, 0x48, 0x6c, 0xfb, 0x37, 0xf5,
	0x0f, 0xac, 0x6c, 0x62, 0xca, 0xf4, 0xb1, 0x4b, 0x7e, 0xdf, 0x39, 0xf6, 0xf1, 0xf9, 0x3e, 0xb8,
	0x79, 0xe1, 0x52, 0x8a, 0xe2, 0xc0, 0x78, 0x24, 0xe2, 0x2c, 0x9a, 0xec, 0x8a, 0x5c, 0xe6, 0x77,
	0x7f, 0x5e, 0x40, 0x6f, 0x76, 0x14, 0x1c, 0xcd, 0x97, 0xd9, 0x36, 0x47, 0x3d, 0x68, 0xca, 0x38,
	0x15, 0xa5, 0xe4, 0xe9, 0x0e, 0xd7, 0x86, 0xd6, 0xa8, 0x89, 0x10, 0x80, 0x39, 0xa0, 0xcc, 0xb0,
	0xa5, 0x99, 0x0d, 0x8d, 0x32, 0xc9, 0x25, 0xcb, 0xf6, 0x29, 0xae, 0x0f, 0xad, 0xd1, 0x25, 0xea,
	0xc2, 0xf5, 0x5b, 0x9e, 0x48, 0x1e, 0x09, 0x7c, 0x61, 0x40, 0xb0, 0x2f, 0x0a, 0x91, 0x49, 0x7c,
	0xa9, 0x01, 0x02, 0x90, 0x22, 0xdd, 0x15, 0x5c, 0xee, 0x0b, 0x81, 0xaf, 0x4c, 0x91, 0x48, 0xf8,
	0xae, 0x14, 0x21, 0xbe, 0xd6, 0xa0, 0x0f, 0xad, 0x30, 0x2e, 0x83, 0x57, 0x5e, 0x44, 0x71, 0x16,
	0xe1, 0x86, 0x81, 0xec, 0xac, 0xb5, 0xa9, 0xa1, 0x0d, 0x0d, 0x66, 0x6e, 0x04, 0x4d, 0x3e, 0x41,
	0x9f, 0x6d, 0xf7, 0x49, 0x32, 0x57, 0xdd, 0x22, 0xe0, 0x3b, 0x1e, 0xc4, 0xf2, 0x80, 0x5b, 0x5a,
	0xfc, 0x06, 0x10, 0x2b, 0x44, 0xca, 0xe3, 0x2c, 0xce, 0xa2, 0x93, 0xf6, 0x51, 0x6b, 0x03, 0xe8,
	0x32, 0xfe, 0x26, 0x0a, 0x1e, 0x09, 0x33, 0x72, 0xfb, 0x74, 0x71, 0x70, 0x08, 0x12, 0x11, 0xe4,
	0xfb, 0x4c, 0xe2, 0x8e, 0x86, 0x18, 0x6c, 0xf6, 0x92, 0x96, 0x25, 0xdf, 0x0a, 0x79, 0xf0, 0x25,
	0x97, 0xfb, 0x12, 0x77, 0xb5, 0xd2, 0x83, 0xa6, 0x52, 0xb6, 0x09, 0x8f, 0x4a, 0x6c, 0x6b, 0xf4,
	0x13, 0x74, 0x58, 0xb5, 0xbd, 0xf2, 0x58, 0xda, 0x1b, 0x5a, 0xa3, 0xce, 0x14, 0x4f, 0x1e, 0x88,
	0xe3, 0x51, 0x36, 0x23, 0x0e, 0x65, 0x33, 0x87, 0x52, 0xe2, 0x3d, 0xb3, 0xb9, 0xbb, 0x20, 0xe8,
	0x3b, 0x68, 0x33, 0xfd, 0x7e, 0x51, 0x35, 0x20, 0xdd, 0xd0, 0x99, 0xcc, 0x1f, 0x1c, 0xef, 0x9e,
	0x30, 0x9f, 0x3a, 0x74, 0xe3, 0xa3, 0x1f, 0xa0, 0xcd, 0x44, 0xc6, 0x5f, 0x12, 0x53, 0xd6, 0xd7,
	0x65, 0xb7, 0x13, 0xb2, 0x76, 0x66, 0x2b, 0xc2, 0x66, 0xae, 0xe7, 0xb9, 0xbf, 0x9b, 0x6a, 0xf5,
	0x10, 0x65, 0x58, 0x55, 0x7b, 0x63, 0x0c, 0x61, 0xa1, 0x28, 0x65, 0x91, 0x1f, 0x44, 0x88, 0x6f,
	0x8d, 0x21, 0xec, 0x95, 0x97, 0x2f, 0x69, 0x89, 0xbf, 0xd2, 0xa0, 0x03, 0x57, 0xac, 0xe0, 0x61,
	0x9c, 0xe3, 0x81, 0xfa, 0xbf, 0xfb, 0x0c, 0xb0, 0xd9, 0x25, 0x39, 0x0f, 0x75, 0x5c, 0x7e, 0x84,
	0xfe, 0xfb, 0x70, 0xb1, 0x38, 0xdb, 0xe6, 0xb8, 0x36, 0xac, 0x8f, 0x5a, 0x53, 0x34, 0xf9, 0x57,
	0xbe, 0xee, 0x42, 0xb0, 0x17, 0x95, 0xbf, 0xc2, 0x17, 0x52, 0xc6, 0x59, 0xa4, 0xe6, 0x48, 0x79,
	0xf0, 0x1a, 0x67, 0x82, 0xc5, 0x61, 0x15, 0xba, 0xf3, 0x80, 0x59, 0x95, 0xbb, 0xf5, 0x20, 0x0d,
	0x75, 0xda, 0xd4, 0x36, 0x16, 0x4b, 0xbf, 0x5a, 0xc8, 0xfc, 0x71, 0x81, 0xda, 0x70, 0x99, 0x88,
	0x37, 0x91, 0x1c, 0xb3, 0x77, 0x17, 0x43, 0xe3, 0xd1, 0xbf, 0x67, 0x33, 0x77, 0xf1, 0x8c, 0x06,
	0x70, 0x21, 0x0f, 0x3b, 0xa1, 0xcf, 0xed, 0x4c, 0x9b, 0x13, 0x25, 0xd0, 0xe7, 0x27, 0x82, 0xbe,
	0x85, 0xeb, 0xfd, 0xee, 0x38, 0xaf, 0x35, 0xac, 0x8d, 0x5a, 0xd3, 0xd6, 0xe4, 0xec, 0x65, 0xdf,
	0xeb, 0x20, 0xb2, 0xf2, 0x38, 0x23, 0xae, 0xeb, 0x8a, 0xde, 0xe4, 0x9f, 0xc3, 0x8f, 0xff, 0xb0,
	0x60, 0xf0, 0x7f, 0x56, 0xf6, 0xa0, 0xfd, 0x30, 0x9b, 0x55, 0x1e, 0x30, 0xf7, 0x57, 0xfb, 0x03,
	0xea, 0x43, 0x57, 0x21, 0x97, 0x3e, 0x10, 0x8f, 0x11, 0xcf, 0x73, 0x3d, 0xbb, 0x86, 0xbe, 0x86,
	0x5b, 0x05, 0x29, 0x79, 0x7c, 0x22, 0x9e, 0x43, 0x37, 0x1e, 0xa9, 0x24, 0x0b, 0xdd, 0x42, 0x4f,
	0x49, 0xbf, 0xb9, 0x2b, 0xea, 0xdc, 0x1b, 0x5c, 0x37, 0x78, 0xbe, 0xf1, 0x3c, 0xb2, 0xa6, 0x15,
	0xbe, 0x40, 0x18, 0x6e, 0x34, 0x7e, 0x9e, 0xaf, 0xc8, 0xdc, 0xdd, 0x9c, 0x14, 0x15, 0xf1, 0xbe,
	0x52, 0x96, 0x6b, 0x4a, 0xbc, 0x2f, 0xce, 0xdc, 0x9c, 0x74, 0x85, 0x10, 0x74, 0x94, 0xa0, 0x56,
	0x55, 0xb1, 0x6b, 0xc3, 0x56, 0xcb, 0xb5, 0xa9, 0x6b, 0xa0, 0x4f, 0x30, 0x38, 0xd5, 0x39, 0xeb,
	0xc5, 0xb9, 0xd8, 0x1c, 0xff, 0x02, 0xed, 0xf7, 0xe9, 0xfc, 0x08, 0x8d, 0xcd, 0xfa, 0x88, 0xec,
	0x9a, 0xfa, 0xd3, 0xdf, 0xcb, 0xf5, 0xbd, 0x6d, 0xa1, 0x2e, 0xb4, 0x8c, 0x79, 0x0a, 0xd4, 0xc7,
	0x9f, 0xe1, 0xe6, 0x3f, 0x43, 0xdb, 0x83, 0x76, 0xc5, 0x8f, 0xc0, 0xfe, 0xa0, 0x26, 0x5b, 0x2c,
	0xfd, 0x73, 0x56, 0x1b, 0xff, 0x0c, 0xed, 0xf7, 0x61, 0xe8, 0x43, 0xd7, 0xa7, 0xca, 0x91, 0x13,
	0xb6, 0x6b, 0xaa, 0xd3, 0xa7, 0xee, 0xd3, 0x19, 0xb3, 0xc6, 0xd3, 0x63, 0x4c, 0x74, 0x1a, 0xba,
	0xd0, 0xda, 0x3c, 0xad, 0x5c, 0x67, 0xc1, 0x96, 0xeb, 0x2f, 0xae, 0x5d, 0x53, 0x2b, 0xfe, 0xfb,
	0x58, 0x9f, 0x50, 0xaa, 0xa7, 0xff, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x08, 0xac, 0x23, 0x4f, 0x4d,
	0x05, 0x00, 0x00,
}
